### ISSUE TITLE
Permalinks to page sections?

### ISSUE THREAD

**Issue by jywarren** [publiclab/community-toolbox#223]
Often in Markdown, we get anchors on headings so we can link down to them, which is convenient! They look like this on Publiclab.org (we added some nice icons using JS and CSS, to show that they exist):

![image](https://user-images.githubusercontent.com/24359/59772864-94b3fd80-927a-11e9-83fb-122cbe008572.png)

(see this example at https://publiclab.org/wiki/simple-air-sensor#Uses)

And typically cause the URL of the page to show a hash like `example.com#Uses`

That leads to `<h2>Uses</h2>` -- although it can be overridden with an anchor tag like: `<h2 a="mypermalink">Uses</h2>` for a url like `example.com#mypermalink`.

Because we use hashes for determining project and repo, are we not able to use the for their original purpose of linking deep down the page? Could this be a reason to use a different kind of hashing, like possibly true GET parameters that we parse from the title, like:

`https://code.publiclab.org?r=all#Candidates` ?

What do you think?

**Comment by Rishabh570** [comment]
Yeah, so permalink is definitely a plus to user convenience. Maybe if we can make use of `urlHash` to implement that would be great but we can also work with params through URL object...I'll take a look.

**Comment by Rishabh570** [comment]
@jywarren To achieve this, we might need to stop putting every piece of info in the URL (like repo and other info), so it might end up looking like this,

`https://code.publiclab.org/#learnourprocess` (for any repo selected!).

As far as the user's knowledge of current repository selected is concerned, the dropdown input shows clearly which repository's data is currently present. So it can be one of the possibility, what do you think about it?

**Comment by jywarren** [comment]
Hmm. Yes, however this would mean it's no longer possible to pass a URL to
a friend or to someone just learning about our code, with specific repos
already selected. For example it's pretty neat to be able to send people
https://code.publiclab.org/#r=all&o=oshwa (although this doesn't seem to be
working...)

**Comment by Rishabh570** [comment]
> this would mean it's no longer possible to pass a URL to
a friend or to someone just learning about our code, with specific repos
already selected.

Yes, that was my concern...so what if we show the URL as `https://code.publiclab.org/oshwa/all/#permalink`? This would mean we need to modify `urlHash.js`.

> https://code.publiclab.org/#r=all&o=oshwa (although this doesn't seem to be
working...)

Yeah, so it's because the repos that are already stored in the DB are being picked up by the code...we need to save data _org_ specific, so I guess instead of saving repos by the key `repos`, we should do `org_name-repos`.

I'll surely get on these two issues after stale issues and recent contribs logic refactorization PR.

**Comment by Rishabh570** [comment]
I'm pushing the changes to `gh-pages`.

**Comment by Rishabh570** [comment]
I'm facing some issue while pushing to `gh-pages`, it says `Updates were rejected because the tip of your current branch is behind hint: its remote counterpart. Integrate the remote changes (e.g. hint: 'git pull ...') before pushing again.` I have merged main into gh-pages so now gh-pages on my machine is at the latest commit, also haven't done `rebase` on gh-pages branch, don't know the reason...

**Comment by Rishabh570** [comment]
Nevermind, pushed successfully! :tada:

**Comment by jywarren** [comment]
But can we run URLs like code.publiclab.org/oshwa/all/#permalink from
gh-pages? by what mechanism? I may just be a little out of date on what's
possible with routing in gh-pages or JS :-P

**Comment by akanksha-v** [comment]
@jywarren I think we can close this issue as it's been resolved. 

![permalinks](https://user-images.githubusercontent.com/59011370/102646155-9620f780-4189-11eb-8ff0-172295079f9e.png)

**Comment by jywarren** [comment]
Thank you! Grateful for the help!
