### ISSUE TITLE
List PRs that could use some review or help -- by folks who've completed one themselves!

### ISSUE THREAD

**Issue by jywarren** [publiclab/community-toolbox#3]
We could add a "Want to review PR" section on code.publiclab.org which will show the PR's where there is no feedback provided. Or, those PR's which are inctive from a month or so.

What do you think @Rishabh570?

**Comment by gauravano** [comment]
@jywarren

**Comment by Rishabh570** [comment]
Ohh sorry I've somehow missed to reply here...
@gauravano @jywarren Yeah, this would be cool...actually, we have a whole lot of opportunities because of the rich JSON that Github gives us. This would surely be beneficial and helpful because we would be able to have a better picture of our progress and time friction between opening a PR and it being reviewed will decrease...
This could be a great follow-up issue when the MVC part gets done...What do you guys think about this?

**Comment by Rishabh570** [comment]
Yeah, I agree...we should think about the breakpoints for issues.

Fetching and selecting those PRs that are inactive for quite a while can be based upon the timestamp (or datestamp) of the last comment on that PR (need to go through the JSON that Github returns when we query for PRs for a repo). Showing that on the page can be another issue.
