### ISSUE TITLE
Weekly community Check-In #43 - Exciting Moments at PL

### ISSUE THREAD

**Issue by cesswairimu** [publiclab/community-toolbox#308]
Happy new year everyone :tada: :tada: 👋

We all at Public Lab 🎈 - learn, grow, work, brainstorm ideas, contribute together so why not share about our weekly goals and the awesome work we have done at Public Lab with each other, so we can support and collaborate with each other better. We have a Community Check-In each week, where every community member can share something about their work from the past week and about their current week's goal 🎯 . You are also welcome to share fun-fact 😄 , new ideas 💡 , your learning goals ☑️.

We believe in collaborative efforts to support our community. We are running a learning platform which helps a newcomer to become master of tomorrow. 💯

##  Exciting Moments at PublicLab
This week share an exciting moment you have had on PublicLab. Could be a feature that you worked on that got you super excited, an Interaction you had with another collaborator, an open call that was very exciting for you, an issue that you raised that got you excited, an eureka moment you had when working on an issue, anything really.

## This week's focus Issues
_This section is not doing so well...But we still have two issues if you are interested in taking up these issues_
These are issues that are of high priority and requests from our 
large community that use the software. https://github.com/publiclab/Leaflet.DistortableImage/labels/high-priority
 We will very much appreciate any help on these issues. Any contributor who is looking for issues to work on please consider taking a look at these. Or you can add more context to the ones labeled `gci-candidate` so that they can be taken up by the gci folks.  We will add a thank you message here in next week's check-in if you contribute to any of these. Thanks in advance :smile: 

### Thank you note to focus issues contributors

Thanks  so much @jywarren  for working on  https://github.com/publiclab/Leaflet.DistortableImage/issues/473 :1st_place_medal: 

## Next Check-in

If you would like to open the next check-in..Leave a comment below. We are happy to help if its your first time

**Thanks everyone for making Public Lab awesome** :balloon: 
Have a great week and year ahead all :heart:

**Comment by cesswairimu** [comment]
@dmahajan980, @bryceparkman, @dependabot-preview[bot], @nicoleiocana, @0dim, @Uzay-G, @nstjean, @AnshitaVishwa, @tsparksh, @sharmamansi, @polygonart6777, @anthony-zhou, @cesswairimu, @chen-robert, @leesgrey, @smarty1palak, @VladimirMikulic, @nfarve, @jywarren, @chanchalsaini, @johnaceto, @gireeshcse, @lisaschumann, @shashwataggarwal, @yeo-yeo, @gabrielrumiranda, @mikepetridisz, @GarvinH, @Ugtan, @sap143, @arjunshekhawat5, @sagarpreet-chadha, @ami-friedman, @gautamig54, @shubhankarsharma00, @rebecarancan, @swathi-0901

**Comment by cesswairimu** [comment]
@Rishabh570 @sashadev-sky @IshaGupta18 @vaibhavmatta @shubhscoder @aSquare14 @sidntrivedi012 @stefannibrasil @ViditChitkara @tech4GT @mridulnagpal @CoderJolly @namangupta01 @sagarpreet-chadha @Souravirus @MayankKashyap @siaw23 @ryzokuken @icarito @steviepubliclab, @ebarry, @jywarren, @sagarpreet-chadha, @JonathanXu1 @rexagod, @divyabaid16, @dinaelhanan, @oorjitchowdhary @publiclab/mentors @publiclab/image-sequencer-guides @publiclab/leaflet-environmental-layers-guides @Paarmita @publiclab/reviewers @Divy123 @bhavayAnand9 @Mridul97 @avsingh999 @Dhiraj240 @codeIriss @IgorWilbert @pdurbin @HarshKhandeparkar @niravasher @publiclab/reviewers @publiclab/is-reviewers @publiclab/community-reps @divyabaid16 @publiclab/community-reps @subhahu123 @govindjeevan @gautamig54 @rarrunategu1 @CleverFool77 @milaaraujo @kevinzluo @U04JSLM59

**Comment by nstjean** [comment]
Hello all! Welcome to the new year!!

I am working on getting some pull requests merged (having some testing challenges!) for the /map/ page. I'll need to add some tests for the map at /post/ and then I'm working on getting markers and popups on /map/.

I've been excited a lot lately because I just really love doing full-stack coding again. :heart: And it has been really really nice to work with other people, including my fabulous co-intern @crisner ! I feel like we're making good progress on our project(s) and it's great to see.

**Comment by jywarren** [comment]
You two are doing amazingly well! 🎉 

Thanks for opening this up Cess! I'll share an excitement from a few years ago that I've already shared, but it never gets old! It was the moment the first person wrote back to a `first-timers-only` issue that I made! It happened within just a couple hours and i was like WHOA, THIS WORKS!?

**Comment by Uzay-G** [comment]
>  I'll share an excitement from a few years ago that I've already shared, but it never gets old! It was the moment the first person wrote back to a first-timers-only issue that I made! It happened within just a couple hours and i was like WHOA, THIS WORKS!?

That's hilarious :smile:. I hope one day I can also welcome other new contributors! 
I have been working on a few complicated oauth issues with the useful help of @SidharthBansal through https://github.com/publiclab/plots2/pulls/7113 and  https://github.com/publiclab/plots2/pulls/7072. I'm also trying to understand how we can make codecov function better and I am discussing with @jywarren on how we can stop it from failing small pull requests. 

Happy new year! :tada:

**Comment by nstjean** [comment]
@Uzay-G You've been doing great work!

**Comment by emilyashley** [comment]
Hi, I'm Emily. Exciting moments at Public Lab? I'd definitely have to say joining the team as full stack developer -- yesterday was my first day 🎉 Also un-related to code, a while ago in 2015 I participated in an aerial mapping of Bayou Bienvenue here in New Orleans with a kite and that was awesome!

**Comment by cesswairimu** [comment]
One of the exciting moments at PublicLab has to be the first open call..meeting everyone on open call and putting a voice to the github names was an exciting moment also helping out new contributors get started on the projects is always an exciting moment for me

**Comment by nstjean** [comment]
Welcome @emilyashley !!

**Comment by crisner** [comment]
One of the exciting moments I had recently at PublicLab was fixing a build error. We had updated LEL which had changes to file path that had been referenced in the plots2 repo and had missed updating one of the files that still referenced the old path. I had to combine commits from two unmerged pull requests, which I had never done before and didn't even know was possible, and I had to figure out why the build was failing in Travis. I had only heard of Travis and continuous integration before I started my internship. So it was exciting to work on this and fix the issue. Also, I work mostly in LEL and rails is still new to me, so having a chance to look into plots2 to find the issue was exciting too.

**Comment by VladimirMikulic** [comment]
Wow, good job @crisner :+1:

**Comment by skilfullycurled** [comment]
Hey everyone, I want to introduce @shipcy and @sunguru98 who each completed an FTO on two related features (#6962 and #7109 respectively) and had those features merged (#7137 and #7128)!  

@shipcy and @sunguru98, please introduce yourselves.  Well, in the case of @shipcy, it's actually a re-introduction because they introduced themselves the day before the new check-in so no one saw it.  Sorry to make you do it a third time @shipcy!

Special thanks to @nstjean, @cesswairimu, @jywarren, and @Uzay-G.  Also, @ebarry and @bronwen9 for their tireless moderation, we hope the process better!  And finally, @nicoleiocana, who unfortunately had to play the role of "mistakenly banned user" which brought the issue to the fore.  Your sacrifice was not in vain @nicoleiocana!  We now have two new contributors and two new features to boot!

**Comment by skilfullycurled** [comment]
Oh, ha!  I didn't realize that this week's question was about exciting moments!  Well, it was very exciting for me to see @shipcy and @sunguru98's issues be merged.  However, my most exciting moment is probably when I had my first PR request merged.  So exciting it was, that I procrastinated completing the project by creating this gif about it.  It made into into my project presentation so I guess you could still consider it work.  : P

I posted it in some thread but I can't find it so here it is again:

![pr_5459_its_merrrrged](https://user-images.githubusercontent.com/950291/72212798-4170f900-34b1-11ea-9169-9aea693827c2.gif)

**Comment by sunguru98** [comment]
Thank you sooooo much for the warm welcome and for accepting me as a part of your community. I usually have this thought of getting judged in OSCs. But they were completely untrue here. Firstly I am a MERN stack developer/Instructor from Coimbatore//India who teaches and builds eCommerce and single-page applications for a living. I have started this dev journey from 2017. 3 years and still going strong. I would like to thank @skilfullycurled and @jywarren for treating new peeps as their own family members and encouraging them to do stuff.

**Comment by shipcy** [comment]
Thank you so much for helping me @skilfullycurled. You are a wonderful person who is always ready to help.
And I would like to thank @nstjean and @jywarren as well. These people also helped me a lot. I thought earlier that people here in open source are not so helpful and no one will guide me because of this, I had not yet contributed. But I was wrong.

I'm currently a junior pursuing Computer Science and Engineering from Delhi Technological University, New Delhi, India. My skillset includes HTML, CSS, JavaScript, C++, jQuery, Node.js, MongoDB, MySQL and frameworks like Express, Bootstrap, etc.

Thanks.

**Comment by cesswairimu** [comment]
Moved to https://github.com/publiclab/mapknitter/issues/1199#issuecomment-573803389 Thanks everyone

**Comment by jywarren** [comment]
Thanks all for introducing yourself and for the wonderful collaboration! ❤️
